//! Lifts the items this harness tests out of the real crosvm sources, by name.
//!
//! `MediaDeviceKind` sits inside `devices/src/virtio/media.rs` and `MediaDeviceConfig` inside
//! `src/crosvm/config.rs`; both crates are far too large to build under cargo on the dev box
//! (logs/vpu_wp/M2.md §5.3), and neither item can be `#[path]`-included on its own. So the text
//! is extracted here at build time -- so that what is tested is what is committed, and a rename
//! is a build failure rather than a stale copy quietly passing.

use std::fmt::Write as _;
use std::path::PathBuf;

/// crosvm's checkout. `@W@` is rewritten by deploy/vpu/harness.sh.
const CROSVM: &str = "@W@/crosvm";

/// `(file, item header as it is written, ...)` -- every item this harness needs, in order.
const ITEMS: &[(&str, &str)] = &[
    ("devices/src/virtio/media.rs", "pub enum MediaDeviceKind {"),
    ("devices/src/virtio/media.rs", "pub enum MediaDeviceSupport {"),
    ("devices/src/virtio/media.rs", "impl MediaDeviceKind {"),
    ("devices/src/virtio/media.rs", "mod media_device_kind_tests {"),
    ("src/crosvm/config.rs", "pub struct MediaDeviceConfig {"),
    (
        "src/crosvm/config.rs",
        "pub fn from_key_values<'a, T: Deserialize<'a>>(value: &'a str) -> Result<T, String> {",
    ),
    ("src/crosvm/config.rs", "mod media_device_config_tests {"),
];

/// The item `header` starts, with the attributes and doc comment directly above it, up to the
/// first line that is exactly `}` -- which is where a top-level rustfmt'd item ends.
fn extract(text: &str, header: &str, file: &str) -> String {
    let lines: Vec<&str> = text.lines().collect();
    let start = lines
        .iter()
        .position(|line| line.trim_end() == header)
        .unwrap_or_else(|| panic!("{file}: no line reads `{header}` -- was the item renamed?"));
    let mut first = start;
    while first > 0 {
        let above = lines[first - 1].trim_start();
        if above.starts_with("#[") || above.starts_with("//") {
            first -= 1;
        } else {
            break;
        }
    }
    let end = lines[start..]
        .iter()
        .position(|line| *line == "}")
        .unwrap_or_else(|| panic!("{file}: `{header}` has no closing brace at column 0"))
        + start;
    lines[first..=end].join("\n")
}

fn main() {
    let mut out = String::from(
        "// Generated by build.rs from the real crosvm sources. Do not edit.\n\
         use serde::Deserialize;\n\
         use serde::Serialize;\n\
         use serde_keyvalue::FromKeyValues;\n\n",
    );
    for (file, header) in ITEMS {
        let path = PathBuf::from(CROSVM).join(file);
        println!("cargo::rerun-if-changed={}", path.display());
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        writeln!(out, "// --- {file}: {header}\n{}\n", extract(&text, header, file))
            .expect("writing to a String");
    }
    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("extracted.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
